[package]
name = "rivus-yaml"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {workspace = true}
serde_yaml = {workspace = true}
thiserror = {workspace = true}
dotenvy = {workspace = true}
regex = {workspace = true}

[dev-dependencies]
tempfile = "3.23.0"