[package]
name = "rivus-log"
version = "0.1.0"
edition = "2024"
description = "基于 tracing 的日志与链路追踪封装"
license = "Apache-2.0"

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
serde = { workspace = true }
