[package]
name = "rivus-web"
version = "0.1.0"
edition = "2024"
description = "基于 Axum 的 Web 服务基础"

[dependencies]

tokio = { workspace = true }
axum = { workspace = true }


tracing = { workspace = true }
anyhow = { workspace = true }
